name: Deploy CDK with GitOps

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::122610492430:role/GitOpsIAMRole-GitHubActionsRole4F1BBA26-YAgBUxbxzeWw
          aws-region: us-east-1

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Bootstrap AWS CDK with GitOps
        run: |
          cdk bootstrap \
            --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
            --trust 122610492430 \
            aws://122610492430/us-east-1

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
