name: Deploy Infra with GitOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt  # Asegúrate de que requirements.txt incluye aws-cdk-lib

      - name: Install AWS CDK globally (for npm)
        run: |
          npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::122610492430:role/GitOpsIAMRole-GitHubActionsRole4F1BBA26-YAgBUxbxzeWw
          aws-region: us-east-1

      - name: Synthesize CDK template
        run: |
          source .venv/bin/activate
          cdk synth

      - name: Deploy infrastructure
        run: |
          source .venv/bin/activate
          cdk deploy --require-approval never

      - name: Rollback on failure
        if: failure()
        run: |
          source .venv/bin/activate
          cdk destroy --all --force

      - name: Log errors if deploy fails
        if: failure()
        run: |
          echo "Deployment failed. Check the logs above for more details."
