name: Deploy CDK App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials from a role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::123456789012:role/MyGitHubActionsRole
        aws-region: us-east-1

    - name: Verify IAM Role Connection
      run: aws sts get-caller-identity

    - name: Install dependencies
      run: npm install

    - name: Build CDK
      run: npm run build

    - name: Synthesize CloudFormation Template
      run: cdk synth > template.yaml

    - name: Deploy to AWS
      run: aws cloudformation deploy --template-file template.yaml --stack-name MyS3BucketStack