name: Deploy CDK with GitOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso para hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuración de credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::122610492430:role/GitOpsIAMRole-GitHubActionsRole4F1BBA26-YAgBUxbxzeWw
          aws-region: us-east-1

      # Configuración del entorno Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Instalación de dependencias de Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener un archivo requirements.txt con las dependencias necesarias

      # Instalación de AWS CDK
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # Bootstrapping de AWS CDK
      - name: Bootstrap AWS CDK with GitOps
        run: |
          cdk bootstrap \
            --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
            --trust 122610492430 \
            aws://122610492430/us-east-1

      # Desplegar la infraestructura con CDK
      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
