name: Deploy CDK App
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug paths
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd git-ops/apps/aws-cdk-ts
          npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Synthesize CDK template
        run: |
          cd git-ops/apps/aws-cdk-ts
          npx cdk synth

      - name: Deploy CDK stack
        run: |
          cd git-ops/apps/aws-cdk-ts
          npx cdk deploy --require-approval never
